/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.registrationform.regformdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;




/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name="userDetails"
)
public class UserDetails  implements java.io.Serializable
 {


private Integer id;
private Date dob;
private String email;
private String emerContactLandline;
private String emerContactMobile;
private String emerPersonName;
private String emerRelation;
private String firstname;
private String gender;
private String homeCity;
private String homeDoor;
private String homeLocation;
private Integer homePincode;
private String homeState;
private Integer landline;
private String lastname;
private Integer mobile;
private String officeCity;
private String officeDoor;
private String officeLocation;
private Integer officePincode;
private String officeState;
private String password;
private String username;

    public UserDetails() {
    }



     @Id @GeneratedValue(strategy=IDENTITY)

    

    @Column(name="ID", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="DOB", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    

    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    

    @Column(name="emerContactLandline")
    public String getEmerContactLandline() {
        return this.emerContactLandline;
    }
    
    public void setEmerContactLandline(String emerContactLandline) {
        this.emerContactLandline = emerContactLandline;
    }

    

    @Column(name="emerContactMobile")
    public String getEmerContactMobile() {
        return this.emerContactMobile;
    }
    
    public void setEmerContactMobile(String emerContactMobile) {
        this.emerContactMobile = emerContactMobile;
    }

    

    @Column(name="emerPersonName")
    public String getEmerPersonName() {
        return this.emerPersonName;
    }
    
    public void setEmerPersonName(String emerPersonName) {
        this.emerPersonName = emerPersonName;
    }

    

    @Column(name="emerRelation")
    public String getEmerRelation() {
        return this.emerRelation;
    }
    
    public void setEmerRelation(String emerRelation) {
        this.emerRelation = emerRelation;
    }

    

    @Column(name="firstname")
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    

    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    

    @Column(name="homeCity")
    public String getHomeCity() {
        return this.homeCity;
    }
    
    public void setHomeCity(String homeCity) {
        this.homeCity = homeCity;
    }

    

    @Column(name="homeDoor")
    public String getHomeDoor() {
        return this.homeDoor;
    }
    
    public void setHomeDoor(String homeDoor) {
        this.homeDoor = homeDoor;
    }

    

    @Column(name="homeLocation")
    public String getHomeLocation() {
        return this.homeLocation;
    }
    
    public void setHomeLocation(String homeLocation) {
        this.homeLocation = homeLocation;
    }

    

    @Column(name="homePincode")
    public Integer getHomePincode() {
        return this.homePincode;
    }
    
    public void setHomePincode(Integer homePincode) {
        this.homePincode = homePincode;
    }

    

    @Column(name="homeState")
    public String getHomeState() {
        return this.homeState;
    }
    
    public void setHomeState(String homeState) {
        this.homeState = homeState;
    }

    

    @Column(name="landline")
    public Integer getLandline() {
        return this.landline;
    }
    
    public void setLandline(Integer landline) {
        this.landline = landline;
    }

    

    @Column(name="lastname")
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    

    @Column(name="mobile")
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }

    

    @Column(name="officeCity")
    public String getOfficeCity() {
        return this.officeCity;
    }
    
    public void setOfficeCity(String officeCity) {
        this.officeCity = officeCity;
    }

    

    @Column(name="officeDoor")
    public String getOfficeDoor() {
        return this.officeDoor;
    }
    
    public void setOfficeDoor(String officeDoor) {
        this.officeDoor = officeDoor;
    }

    

    @Column(name="officeLocation")
    public String getOfficeLocation() {
        return this.officeLocation;
    }
    
    public void setOfficeLocation(String officeLocation) {
        this.officeLocation = officeLocation;
    }

    

    @Column(name="officePincode")
    public Integer getOfficePincode() {
        return this.officePincode;
    }
    
    public void setOfficePincode(Integer officePincode) {
        this.officePincode = officePincode;
    }

    

    @Column(name="officeState")
    public String getOfficeState() {
        return this.officeState;
    }
    
    public void setOfficeState(String officeState) {
        this.officeState = officeState;
    }

    

    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    

    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof UserDetails) )
		 return false;

		 UserDetails that = ( UserDetails ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

