
package com.registrationform.regformdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface RegFormDBQueryExecutorService {
    Page<Object> executeUsernameExistCheck(Pageable pageable, java.lang.String username) throws QueryParameterMismatchException;
    Page<Object> executeEmailIDexistCheck(Pageable pageable, java.lang.String emailID) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

