
package com.registrationform.regformdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class RegFormDBQueryExecutorServiceImpl implements RegFormDBQueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(RegFormDBQueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("regFormDBWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "regFormDBTransactionManager")
	@Override
	public Page<Object> executeUsernameExistCheck(Pageable pageable, java.lang.String username)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("username", username);
        return queryExecutor.executeNamedQuery("usernameExistCheck", params, pageable);
	}
	@Transactional(value = "regFormDBTransactionManager")
	@Override
	public Page<Object> executeEmailIDexistCheck(Pageable pageable, java.lang.String emailID)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("emailID", emailID);
        return queryExecutor.executeNamedQuery("emailIDexistCheck", params, pageable);
	}

	@Transactional(value = "regFormDBTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "regFormDBTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

